<?php require 'templates/formulario_agregar_categoria.phtml'; ?>

<h1>Lista de Categorías</h1>
    <ul class="list-group">
        <?php foreach ($categorias as $categoria) { ?>  
            <li class="list-group-item item-categoria <?php if($categoria->suspendida): ?> suspender <?php endif ?>"> 
                <div class="label">
                    <b><?= htmlspecialchars($categoria->nombre_categoria )?></b> | <a href="mostrar_item/<?= $categoria->ID_categoria ?>">Ver Productos</a>
                </div>
                <div class="actions">
                    <?php if(!$categoria->suspendida): ?>
                        <a href="editar_categoria/<?= $categoria->ID_categoria ?>" type="button" class='btn btn-success btn-sm ml-auto'>Suspender</a>
                    <?php else: ?>
                        <span class="btn btn-secondary btn-sm ml-auto" disabled>Suspender</span>
                    <?php endif ?> 
                    <a href="eliminar_categoria/<?= $categoria->ID_categoria ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Eliminar</a>
                </div>     
            </li>
        <?php } ?>     
    </ul> 

<?php require 'templates/layout/footer.phtml'; 


