<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='POST' action='login'>
    <div class='alert alert-info' role='alert'>
        Es necesario el inicio de sesión para realizar algún cambio. Por favor, complete los campos a continuación.
    </div>

    <div class='form-group'>
        <label for='nombre'>Usuario</label>
        <input type='text' class='form-control' id='nombre' name='nombre' required>
    </div>

    <div class='form-group'>
        <label for='contraseña'>Contraseña</label>
        <input type='password' class='form-control' id='contraseña' name='contraseña' required>
    </div>

    <button type='submit' class='btn btn-primary btn-sm mt-2'>Iniciar Sesion</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>
