<form action="agregar_categoria" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Ingrese una nueva Categoría</label>
                <input required name="nombre_categoria" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <button type="submit" class="btn btn-primary btn-sm mt-2">Agregar</button>
        </div>
    </div>
</form>

           
 


