<?php require 'templates/layout/header.phtml'; ?>

<div class="text-center">
    <h1>Bienvenido al Catálogo 2024</h1>
    <p>Descubre una amplia variedad de productos organizados por categorías.</p>
    <p>Haz clic en el botón de abajo para explorar nuestras categorías.</p>
    <a href="lista_categorias" class="btn btn-primary">Ver Categorías</a>
</div>

<?php require 'templates/layout/footer.phtml'; ?>
