<?php require 'templates/layout/header.phtml'; ?>

<h1>Lista de todos los Productos</h1>
    <ul class="list-group">
        <?php foreach ($productos as $producto) { ?>  
            <li class="list-group-item item-producto <?php if($producto->sin_stock): ?> sin_stock <?php endif ?>">
                <div class="label">
                    <b><?= htmlspecialchars($producto->nombre_producto) ?></b> | Categoria <?= $producto->nombre_categoria ?> | <a href="producto/<?= $producto->ID_producto ?>">Ver Detalle</a>
                </div>
            </li>
        <?php } ?>
    </ul> 
        
<?php require 'templates/layout/footer.phtml'; 

    
            
                
                   
              
                
            




